{
	"version": 1504529106,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/logo-sheet0.png",
		"images/fundomenu-sheet0.png",
		"images/buttonplay-sheet0.png",
		"images/buttoninstrucoes-sheet0.png",
		"images/buttoninfo-sheet0.png",
		"images/love-sheet0.png",
		"images/code-sheet0.png",
		"images/peca-sheet0.png",
		"images/peca-sheet1.png",
		"images/escolacompleta-sheet0.png",
		"images/sensor-sheet0.png",
		"images/pecafase2-sheet0.png",
		"images/sensor3-sheet0.png",
		"images/peca3-sheet0.png",
		"images/peca3-sheet1.png",
		"images/sprite2-sheet0.png",
		"images/sensor2-sheet0.png",
		"images/particles.png",
		"images/imapa-sheet0.png",
		"images/iescolamapa-sheet0.png",
		"images/icafemapa-sheet0.png",
		"images/ilanhousemapa-sheet0.png",
		"images/icontinuar-sheet0.png",
		"images/tcont.png",
		"images/bjogarnovamente-sheet0.png",
		"images/sprite-sheet0.png",
		"images/pecas4-sheet0.png",
		"images/pecas4-sheet1.png",
		"images/sprite3-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sensor4-sheet0.png",
		"images/ipraçamapa-sheet0.png",
		"images/semtítulo-sheet0.png",
		"images/escolapng-sheet0.png",
		"images/lanhouse-sheet0.png",
		"images/telanarracao-sheet0.png",
		"images/logotipobodes-sheet0.png",
		"images/icoreperdeu-sheet0.png",
		"images/iperso2-sheet0.png",
		"images/icore-sheet0.png",
		"images/buttonvoltar-sheet0.png",
		"images/puzzle35098_960_-sheet0.png",
		"images/troca-sheet0.png",
		"images/touchgesturetapalternate-sheet0.png",
		"images/tap-sheet0.png",
		"images/rt-sheet0.png",
		"media/220166__gameaudio__button-confirm-spacey.m4a",
		"media/220166__gameaudio__button-confirm-spacey.ogg",
		"media/ganhou- (online-audio-converter.com).ogg",
		"media/menu (online-audio-converter.com).ogg",
		"media/ganhou- (online-audio-converter.com).m4a",
		"media/menu (online-audio-converter.com).m4a",
		"media/perdeu (online-audio-converter.com).m4a",
		"media/perdeu (online-audio-converter.com).ogg",
		"media/perdeupart2 (online-audio-converter.com).m4a",
		"media/perdeupart2 (online-audio-converter.com).ogg",
		"media/10convert.com_efeito-voltando-a-fita_m02j6wiurd8 (online-audio-converter.com).m4a",
		"media/10convert.com_efeito-voltando-a-fita_m02j6wiurd8 (online-audio-converter.com).ogg",
		"media/ctem (online-audio-converter.com).m4a",
		"media/ctem (online-audio-converter.com).ogg",
		"media/254315__jagadamba__clock-tick.m4a",
		"media/254315__jagadamba__clock-tick.ogg",
		"media/bodeberrando- (online-audio-converter.com).m4a",
		"media/bodeberrando- (online-audio-converter.com).ogg",
		"media/escrita- (online-audio-converter.com).m4a",
		"media/escrita- (online-audio-converter.com).ogg",
		"media/efeito sonoro - digitando teclado.m4a",
		"media/efeito sonoro - digitando teclado (online-audio-converter.com).m4a",
		"media/efeito sonoro - digitando teclado (online-audio-converter.com).ogg",
		"media/fundo musical muito romantico (online-audio-converter.com)-[audiotrimmer.com].m4a",
		"media/fundo musical muito romantico (online-audio-converter.com)-[audiotrimmer.com].ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}