{
	"version": 1512644927,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/player-sheet0.png",
		"images/player-sheet1.png",
		"images/inimigos-sheet0.png",
		"images/bala-sheet0.png",
		"images/vitima-sheet0.png",
		"images/particles.png",
		"images/menudesenho-sheet0.png",
		"images/caixademenu-sheet0.png",
		"images/nomedojogo-sheet0.png",
		"images/sprite-sheet0.png",
		"images/bplay-sheet0.png",
		"images/binstru-sheet0.png",
		"images/bcreditos-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/chaomenu.png",
		"images/tanquemenu-sheet0.png",
		"images/tiledbackground.png",
		"images/cima-sheet0.png",
		"images/baixo-sheet0.png",
		"images/esquerda-sheet0.png",
		"images/direita-sheet0.png",
		"images/gramafases-sheet0.png",
		"images/gramafases-sheet1.png",
		"images/logo-sheet0.png",
		"images/nomemenu-sheet0.png",
		"images/capacete-sheet0.png",
		"images/capacete-sheet1.png",
		"images/numerosfases-sheet0.png",
		"images/numerosfases-sheet1.png",
		"images/numerosfases-sheet2.png",
		"images/telafases-sheet0.png",
		"images/canhaoinimigo-sheet0.png",
		"images/aviaomenu-sheet0.png",
		"images/aviaomenu2-sheet0.png",
		"images/plat-sheet0.png",
		"images/solido-sheet0.png",
		"images/telastextos-sheet0.png",
		"images/perdeubonco-sheet0.png",
		"images/breiniciar-sheet0.png",
		"images/bmenu-sheet0.png",
		"images/touchpng-sheet0.png",
		"images/mousepng-sheet0.png",
		"images/tecladfopng-sheet0.png",
		"images/sprite3-sheet0.png",
		"media/click.m4a",
		"media/click.ogg",
		"media/som da cobra para logo (online-audio-converter.com).m4a",
		"media/som da cobra para logo (online-audio-converter.com).ogg",
		"media/som do jogo (online-audio-converter.com).m4a",
		"media/som do jogo (online-audio-converter.com).ogg",
		"media/som tela inicial e final.m4a",
		"media/som tela inicial e final.ogg",
		"media/403920__uso-sketch__arcade-war.m4a",
		"media/403920__uso-sketch__arcade-war.ogg",
		"media/270403__littlerobotsoundfactory__jingle-lose-00.m4a",
		"media/270403__littlerobotsoundfactory__jingle-lose-00.ogg",
		"media/ganhou.m4a",
		"media/ganhou.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}